
<?php
$local_site_name = "Terms of Use and Site Rules";
$local_site_path = "home/temps/terms_tpl.php";

$content_array = array();

$content_array[] = array(
"title" => "Terms of Use - effective beginning 2/7/23",
"anchor" => "terms",
"text" => "<p>By using the site, you agree to the following terms and conditions:<br>
1. You agree with the <a href='index.php?a=privacy'>Privacy Policy</a>.<br>
2. You agree that I (meaning <i>James Gooch, and/or any representative(s) or corporation(s) I employ or select</i>) and/or this website receive a perpetual license and rights to any content, information, feedback, suggestions, or other data that you submit and that I can do anything with or to it/them that I see fit, albeit your intellectual property rights are otherwise unchanged.<br>
3. You agree that you are fully responsible and liable for anything resulting from your use of and submissions to the website.<br>
4. You agree that I am not responsible, liable, or at fault for any content or information available on this site, nor for any harm, including but not limited to physical, social, emotional, spiritual, mental, or financial, resulting from, connected to, or correlated with anyone's use of, or access to the site, legitimate or otherwise, to the fullest extent permitted by Texas and United States law.<br>
5. You agree that everything pertaining to the website is 'as-is' and that there are no promises or guarantees about its suitability or reliability for anyone's purposes.<br>
6. You agree that the site and features are available at my pleasure and that I am not obliged to maintain, preserve, or restore anything available on the website, user-supplied or otherwise.<br>
7. You acknowledge that as a consequence of the above sections, your account, submissions, etc., may be suspended or deleted by me at any time for any or no reason(s). You agree that such actions do not mitigate or nullify your prior agreement to follow any terms, conditions, rules, or guidelines of using the site.</p>");

$content_array[] = array(
    "title" => "Principles of User Content and Conduct",
    "anchor" => "principles",
    "text" => "<p>My interest as an administrator is not preserving users' freedom of speech, but in maintaining a tranquil atmosphere in line with Christian principles. Anything that disturbs my sense of peace, or that I would feel ashamed for any friend or family member to see, tend not to be in line with that.</p>
    <p>This isn't to stifle discussion of serious topics; I want those I interact with to feel comfortable opening up. This isn't to judge those who don't 'measure up' to some standard. It is simply a notice that I'm not inclined to suffer obscene, profane, hostile, disrespectful, and such like conversation if I don't have to, and it seems reasonable that I shouldn't have to on my own website, which you are visiting.</p>
    <p>Someone's attitude and direction are what matters most. A contentious person is not likely to tarry long, but if you are trying to get along and are honestly forgetting, we can work with that.</p>
    ");

$content_array[] = array(
    "title" => "Terms for Copying, Adapting, and Altering Page Assets",
    "anchor" => "alteringterms",
    "text" => "<p>Some who visit this site may be technically inclined, or otherwise inclined to learn from, or adapt, page assets. This section covers the terms for such use. It is in force beginning Oct 25, 2024.</p>
    <h4>1. Basic Rights</h4>
    <p>All rights are initially reserved, to the fullest extent allowed by Texas and United States law. The following sections grant specific rights to you. Rights reserved in earlier sections may be modified by later sections.</p>
    <h4>2. HTML, CSS, and plain JS</h4>
    <p>All HTML tags (not to be confused with elements), classes, and IDs, all CSS files, ordinary JavaScript (meaning code written in the JavaScript programming language and included in a .js file), and all comments, can be used, adapted, or altered, for works without being credited.</p>
    <p>All HTML text that is not structural in nature, such as but not limited to articles, documentation, About sections, names of links, and other writings, is <i>not</i> covered under this clause, and remains reserved.</p>
    <p>All WebAssembly code, whether included in .wasm files or elsewhere, is <i>not</i> covered under this clause, and remains reserved.</p>
    <p>Image files, including those generated by scripts, as well as audio, video, and other similar files not previously or specifically addressed here, are <i>not</i> covered under this clause and remain reserved.</p>
    <h4>3. Code Samples</h4>
    <p>Some pages, such as on gPress, may include code samples in their text. These may consist of either valid language code, or pseudo-code that describe principles of code or logic, that could be translated into a language of the user's choice. Anything encapsulated by HTML &lt;publicdomain&gt; elements, when the page is first delivered from the server, including the HTML markup, the code, and the text, may be used or adapted without being credited.</p>
    <h4>4. Tech Demos</h4>
    <p>An individual tech demo may have its own license. If there is no text that describes different licensing terms, on either the 'Tech Demonstrations' listing page or in the demo itself, the demo falls under the following terms: Everything that is encapsulated in a &lt;publicdomain&gt; HTML element, when the page is first delivered from the server, is treated the same as code samples, as described in section 2. If the same element encapsulates links to CSS or JavaScript files, these assets are under the same license, unless text in the file specifically says otherwise.</p>
    <h4>5. Conclusion</h4>
    <p>These terms are intended to allow people to learn from and adapt basic aspects of the website, and to make use of certain educational resources I've provided, without giving away the rights to my creative works. They are also meant to put scrupulous visitors on a more even footing with those who aren't. I would appreciate credit, but I don't require it because I know it can be a burden; it's easy to be influenced by something, include it in your own work, and then forget exactly where you got it from.</p>
    
    <p>If there is any reserved item that you're desperate to have access to, send me an email about it. I can't promise anything up front, but there's a chance we can work out a deal.</p>
    ");

$local_site_meta = "The Middling Works terms of service, rules, which regulate user interactions with the site, and license agreements."
?>